apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: expense
  labels:
    project: expense
    component: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: db
  template:
    metadata:
      labels:
        project: expense
        component: db
    spec:
      containers:
        - name: nginx
          image: joindevops/mysql:v1.0
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: expense
spec:
  selector:
    project: expense
    component: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
